### PR TITLE
SD card server

### PR DESCRIPTION
**Pull request by LeeLeahy2**
In Base mode, the SD card server will come on shortly after the NTRIP
server starts.  The IP address of the SD card server is output to the
serial port at a regular interval, currently 15 seconds.  Using a web
browser and connecting with HTTP:// to that IP address returns a short
webpage with a link to the SD card listing page.  Clicking on a file
link will cause the file to be downloaded from the SD card to the web
browser.

### CODE REVIEW

**Comment by nseidle** [comment]
I get an HTTP 500 error. I cannot access any file with the current PR.

Steps to reproduce:

* RTK Express
* microSD inserted
* Start in Rover
* Go to Config
* Connect via WiFi from laptop
* Bring up 192.168.4.1
* Click on 'SD Card Files' link
* Get Error 500 in a new tab

Previously I was getting a list of files. A lot has changed and something has broken.

Serial output shows no obvious activity:
image

Settings are being sent to browser, but there is no event handler when the link is clicked.

**Comment by LeeLeahy2** [comment]
The latest update:

1. Fixes the HTTP 500 error by always enabling the SD Card Server during WiFi Config.
2. Adds a checkbox to WiFi Config System Settings that enables or disables the SD Card Server.
3. Adds a checkbox to WiFi Config Base Settings under Survey-In to start WiFi during Survey-In.
4. Updates the Base Configuration NTRIP Server documentation to mention enabling the SD Card Server and enabling WiFi during Survey-In.
5. Updates the GNSS Configuration NTRIP Client documentation to mention enabling the SD Card Server.
6. Updates the Data Logging Documentation to describe enabling the SD Card Server

**Comment by nseidle** [comment]
Stack smash. It's very reproducible for me. Steps to reproduce:

* Factory reset RTK Express
* Put device into config mode from rover
* Access device over AP Wifi
* Open chrome to 192.168.1.4
* Click on system / 'SD Card Files'

New tab opens in browser then spins to infinity. 

Below is serial output. You can see the device send CSV of settings to AP config page, then die once SD is clicked.

16:58:14.808 -> [ 27734][D][RTK_Surveyor.ino:636] updateLogs(): No increase in file size
16:58:15.463 -> settingsCSV len: 2979
16:58:15.463 -> 
settingsCSV: platformPrefix,Express,rtkFirmwareVersion,RTK Express Firmware: v2.3-Jul  6 2022,zedFirmwareVersion,ZED-F9P Firmware: HPG 1.32,measurementRateHz,4.00,dynamicModel,0,ubxConstellationsGPS,true,ubxConstellationsSBAS,true,ubxConstellationsGalileo,true,ubxConstellationsBeiDou,true,ubxConstellationsGLONASS,true,UBX_NMEA_DTM,0,UBX_NMEA_GBS,0,UBX_NMEA_GGA,1,UBX_NMEA_GLL,0,UBX_NMEA_GNS,0,UBX_NMEA_GRS,0,UBX_NMEA_GSA,1,UBX_NMEA_GST,1,UBX_NMEA_GSV,4,UBX_NMEA_RMC,1,UBX_NMEA_VLW,0,UBX_NMEA_VTG,0,UBX_NMEA_ZDA,0,UBX_NAV_ATT,0,UBX_NAV_CLOCK,0,UBX_NAV_DOP,0,UBX_NAV_EOE,0,UBX_NAV_GEOFENCE,0,UBX_NAV_HPPOSECEF,0,UBX_NAV_HPPOSLLH,0,UBX_NAV_ODO,0,UBX_NAV_ORB,0,UBX_NAV_POSECEF,0,UBX_NAV_POSLLH,0,UBX_NAV_PVT,0,UBX_NAV_RELPOSNED,0,UBX_NAV_SAT,0,UBX_NAV_SIG,0,UBX_NAV_STATUS,0,UBX_NAV_SVIN,0,UBX_NAV_TIMEBDS,0,UBX_NAV_TIMEGAL,0,UBX_NAV_TIMEGLO,0,UBX_NAV_TIMEGPS,0,UBX_NAV_TIMELS,0,UBX_NAV_TIMEUTC,0,UBX_NAV_VELECEF,0,UBX_NAV_VELNED,0,UBX_RXM_MEASX,0,UBX_RXM_RAWX,0,UBX_RXM_RLM,0,UBX_RXM_RTCM,0,UBX_RXM_SFRBX,0,UBX_MON_COMMS,0,UBX_MON_HW2,0,UBX_MON_HW3,0,UBX_MON_HW,0,UBX_MON_IO,0,UBX_MON_MSGPP,0,UBX_MON_RF,0,UBX_MON_RXBUF,0,UBX_MON_RXR,0,UBX_MON_TXBUF,0,UBX_TIM_TM2,0,UBX_TIM_TP,0,UBX_TIM_VRFY,0,UBX_RTCM_1005,0,UBX_RTCM_1074,0,UBX_RTCM_1077,0,UBX_RTCM_1084,0,UBX_RTCM_1087,0,UBX_RTCM_1094,0,UBX_RTCM_1097,0,UBX_RTCM_1124,0,UBX_RTCM_1127,0,UBX_RTCM_1230,0,UBX_RTCM_4072_0,0,UBX_RTCM_4072_1,0,UBX_ESF_MEAS,0,UBX_ESF_RAW,0,UBX_ESF_STATUS,0,UBX_ESF_ALG,0,UBX_ESF_INS,0,baseTypeSurveyIn,true,baseTypeFixed,false,observationSeconds,60,observationPositionAccuracy,5.00,ntripServer_StartAtSurveyIn,true,fixedBaseCoordinateTypeECEF,true,fixedBaseCoordinateTypeGeo,false,fixedEcefX,-1280206.568,fixedEcefY,-4716804.403,fixedEcefZ,4086665.484,fixedLat,40.090294790,fixedLong,-105.185057610,fixedAltitude,1560.0890,enableNtripServer,false,ntripServer_CasterHost,rtk2go.com,ntripServer_CasterPort,2101,ntripServer_CasterUser,,ntripServer_CasterUserPW,,ntripServer_MountPoint,bldr_dwntwn2,ntripServer_MountPointPW,WR5wRo4H,ntripServer_wifiSSID,TRex,ntripServer_wifiPW,parachutes,enableNtripClient,false,ntripClient_CasterHost,rtk2go.com,ntripClient_CasterPort,2101,ntripClient_CasterUser,,ntripClient_CasterUserPW,,ntripClient_MountPoint,bldr_SparkFun1,ntripClient_MountPointPW,undefined,ntripClient_wifiSSID,TRex,ntripClient_wifiPW,parachutes,ntripClient_TransmitGGA,true,enableSensorFusion,false,autoIMUmountAlignment,true,enableLogging,true,maxLogTime_minutes,1440,maxLogLength_minutes,1440,enableSdCardServer,false,sdFreeSpaceMB,356,sdUsedSpaceMB,650,enableResetDisplay,true,sdMounted,true,dataPortBaud,460800,radioPortBaud,57600,dataPortChannel,0,hardwareID,B8D61A0DB022,daysRemaining,No Keys,pointPerfectDeviceProfileToken,,enablePointPerfectCorrections,true,home_wifiSSID,,home_wifiPW,,autoKeyRenewal,true,enableExternalPulse,true,externalPulseTimeBetweenPulse_us,900000,externalPulseLength_us,100000,externalPulsePolarity,1,enableExternalHardwareEventLogging,false,profileNumber,2,profileName,HomeAP,
16:58:15.743 -> 
[ 28659][D][Form.ino:262] onWsEvent(): Sending command: platformPrefix,Express,rtkFirmwareVersion,RTK Express Firmware: v2.3-Jul  6 2022,zedFirmwareVersion,ZED-F9P Firmware: HPG 1.32,measurementRateHz,4.00,dynamicModel,0,ubxConstellationsGPS,true,ubxConstellationsSBAS,true,ubxConstellationsGalileo,true,ubxConstellationsBeiDou,true,ubxConstellationsGLONASS,true,UBX_NMEA_DTM,0,UBX_NMEA_GBS,0,UBX_NMEA_GGA,1,UBX_NMEA_GLL,0,UBX_NMEA_GNS,0,UBX_NMEA_GRS,0,UBX_NMEA_GSA,1,UBX_NMEA_GST,1,UBX_NMEA_GSV,4,UBX_NMEA_RMC,1,UBX_NMEA_VLW,0,UBX_NMEA_VTG,0,UBX_NMEA_ZDA,0,UBX_NAV_ATT,0,UBX_NAV_CLOCK,0,UBX_NAV_DOP,0,UBX_NAV_EOE,0,UBX_NAV_GEOFENCE,0,UBX_NAV_HPPOSECEF,0,UBX_NAV_HPPOSLLH,0,UBX_NAV_ODO,0,UBX_NAV_ORB,0,UBX_NAV_POSECEF,0,UBX_NAV_POSLLH,0,UBX_NAV_PVT,0,UBX_NAV_RELPOSNED,0,UBX_NAV_SAT,0,UBX_NAV_SIG,0,UBX_NAV_STATUS,0,UBX_NAV_SVIN,0,UBX_NAV_TIMEBDS,0,UBX_NAV_TIMEGAL,0,UBX_NAV_TIMEGLO,0,UBX_NAV_TIMEGPS,0,UBX_NAV_TIMELS,0,UBX_NAV_TIMEUTC,0,UBX_NAV_VELECEF,0,UBX_NAV_VELNED,0,UBX_RXM_MEASX,0,UBX_RXM_RAWX,0,UBX_RXM_RLM,0,UBX_RXM_RTCM,0,UBX_RXM_SFRBX,0,UBX_MON_COMMS,0,UBX_MON_HW2,0,UBX_MON_HW3,0,UBX_MON_HW,0,UBX_MON_IO,0,UBX_MON_MSGPP,0,UBX_MON_RF,0,UBX_MON_RXBUF,0,UBX_MON_RXR,0,UBX_MON_TXBUF,0,UBX_TIM_TM2,0,UBX_TIM_TP,0,UBX_TIM_VRFY,0,UBX_RTCM_1005,0,UBX_RTCM_1074,0,UBX_RTCM_1077,0,UBX_RTCM_1084,0,UBX_RTCM_1087,0,UBX_RTCM_1094,0,UBX_RTCM_1097,0,UBX_RTCM_1124,0,UBX_RTCM_1127,0,UBX_RTCM_1230,0,UBX_RTCM_4072_0,0,UBX_RTCM_4072_1,0,UBX_ESF_MEAS,0,UBX_ESF_RAW,0,UBX_ESF_STATUS,0,UBX_ESF_ALG,0,UBX_ESF_INS,0,baseTypeSurveyIn,true,baseTypeFixed,false,observationSeconds,60,observationPositionAccuracy,5.00,ntripServer_StartAtSurveyIn,true,fixedBaseCoordinateTypeECEF,true,fixedBaseCoordinateTypeGeo,false,fixedEcefX,-1280206.568,fixedEcefY,-4716804.403,fixedEcefZ,4086665.484,fixedLat,40.090294790,fixedLong,-105.185057610,fixedAltitude,1560.0890,enableNtripServer,false,ntripServer_CasterHost,rtk2go.com,ntripServer_CasterPort,2101,ntripServer_CasterUser,,ntripServer_CasterUserPW,,ntripServer_MountPoint,bldr_dwntwn2,ntripServer_MountPointPW,WR5wRo4H,ntripServer_wifiSSID,TRex,ntripServer_wifiPW,parachutes,enableNtripClient,false,ntripClient_CasterHost,rtk2go.com,ntripClient_CasterPort,2101,ntripClient_CasterUser,,ntripClient_CasterUserPW,,ntripClient_MountPoint,bldr_SparkFun1,ntripClient_MountPointPW,undefined,ntripClient_wifiSSID,TRex,ntripClient_wifiPW,parachutes,ntripClient_TransmitGGA,true,enableSensorFusion,false,autoIMUmountAlignment,true,enableLogging,true,maxLogTime_minutes,1440,maxLogLength_minutes,1440,enableSdCardServer,false,sdFreeSpaceMB,356,sdUsedSpaceMB,650,enableResetDisplay,true,sdMounted,true,dataPortBaud,460800,radioPortBaud,57600,dataPortChannel,0,hardwareID,B8D61A0DB022,daysRemaining,No Keys,pointPerfectDeviceProfileToken,,enablePointPerfectCorrections,true,home_wifiSSID,,home_wifiPW,,autoKeyRenewal,true,enableExternalPulse,true,externalPulseTimeBetweenPulse_us,900000,externalPulseLength_us,100000,externalPulsePolarity,1,enableExternalHardwareEventLogging,false,profileNumber,2,profileName,HomeAP,
16:58:16.025 -> 
16:58:19.577 -> Batt (97%): Voltage: 4.16V Discharging: -7.28%/hr Green
16:58:19.577 -> 
UBX file size: 17332 - Generation rate: 0.0kB/s - Write speed: 0.0kB/s
16:58:19.811 -> [ 32745][D][RTK_Surveyor.ino:636] updateLogs(): No increase in file size
16:58:20.979 -> 
16:58:20.979 -> Stack smashing protect failure!
16:58:21.026 -> 
16:58:21.026 -> 
16:58:21.026 -> abort() was called at PC 0x401225eb on core 1

Below is the stack trace:

Decoding stack results
0x40083da5: panic_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c line 402
0x40095309: esp_system_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c line 121
0x4009a861: abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/abort.c line 46
0x401225eb: __stack_chk_fail at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/stack_check.c line 36
0x40105275: AsyncAbstractResponse::_fillBufferAndProcessTemplates(unsigned char*, unsigned int) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\ESPAsyncWebServer\src\WebResponses.cpp line 384
0x401056ab: AsyncAbstractResponse::_ack(AsyncWebServerRequest*, unsigned int, unsigned int) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\ESPAsyncWebServer\src\WebResponses.cpp line 315
0x4010402e: AsyncAbstractResponse::_respond(AsyncWebServerRequest*) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\ESPAsyncWebServer\src\WebResponses.cpp line 261
0x40102aae: AsyncWebServerRequest::send(AsyncWebServerResponse*) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\ESPAsyncWebServer\src\WebRequest.cpp line 725
0x40107ed9: isSdCardPage(AsyncWebServerRequest*) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\SdCardServer\src\SdCardServer.cpp line 474
0x40107f0f: std::_Function_handler   >::_M_invoke(const std::_Any_data &, AsyncWebServerRequest *&&) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\SdCardServer\src\SdCardServer.cpp line 830
0x401058cd: AsyncCallbackWebHandler::handleRequest(AsyncWebServerRequest*) at c:\users\studio\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\gcc8_4_0-esp-2021r1\xtensa-esp32-elf\include\c++\8.4.0\bits/std_function.h line 682
0x40103735: AsyncWebServerRequest::_parseLine() at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\ESPAsyncWebServer\src\WebRequest.cpp line 581
0x40103845: AsyncWebServerRequest::_onData(void*, unsigned int) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\ESPAsyncWebServer\src\WebRequest.cpp line 123
0x40103a2d: std::_Function_handler   >::_M_invoke(const std::_Any_data &, void *&&, AsyncClient *&&, void *&&, unsigned int &&) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\ESPAsyncWebServer\src\WebRequest.cpp line 76
0x40106c01: AsyncClient::_recv(tcp_pcb*, pbuf*, signed char) at c:\users\studio\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\gcc8_4_0-esp-2021r1\xtensa-esp32-elf\include\c++\8.4.0\bits/std_function.h line 682
0x40106c7d: AsyncClient::_s_recv(void*, tcp_pcb*, pbuf*, signed char) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp line 1210
0x4010753e: _async_service_task(void*) at C:\Users\Studio\Dropbox\Apps\Arduino\libraries\AsyncTCP\src\AsyncTCP.cpp line 162

**Comment by LeeLeahy2** [comment]
Please update to V1.4.0 of the SdCardServer library.

This fixes the issue with partial data being returned.  This change also dynamically allocates some structures that were permanently allocated before.

I am rarely (~1 in 20) seeing a failure which generates a stack smash protect failure.  I have not been able to get the exception decode working.  All I get is a decode failure.

**Comment by LeeLeahy2** [comment]
Found and fixed the stack smash protect failure.

**Comment by nseidle** [comment]
In Config mode: I cannot connect to Web AP page via WiFi on laptop or cell phone to test - IP 192.186.4.1. Looks like something broke, maybe in a re-base but I haven't pinned it down.

In Base Mode I do not see an IP address every 15s:
image

I do see an IP address at first connection, but I don't get a response from 10.8.252.98. It may be the SparkFun mixed/secure WiFi but since the device is not reporting an IP every 15s, I suspect other problems as well.

**Comment by nseidle** [comment]
Got a little further. The AP config page comes up but download fails on 29MB file:

image

FWIW the "assert failed: xQueueGenericSend queue.c" was the same error I fixed in NVM.ino earlier today when the semaphore was not handled correctly (giving back the semaphore twice).

Oddly, the backtrace fails to decode. That's the first time I've see that. The stack trace is also the largest I've ever seen it:

> Backtrace:0x40083da5:0x3ffe8e400x40095309:0x3ffe8e60 0x4009a975:0x3ffe8e80 0x40095da6:0x3ffe8fb0 0x4010ac8d:0x3ffe8ff0 0x400f1a3a:0x3ffe9010 0x400f6ee1:0x3ffe9030 0x400f6751:0x3ffe9050 0x400f6c86:0x3ffe9070 0x400f68ef:0x3ffe9090 0x400f6904:0x3ffe90b0 0x400f6c40:0x3ffe90e0 0x400f6d60:0x3ffe9100 0x400f4d2a:0x3ffe9120 0x40108189:0x3ffe9150 0x4010460e:0x3ffe9170 0x401058ef:0x3ffe91a0 0x40105d43:0x3ffe9230 0x40216792:0x3ffe9290 0x40101ed9:0x3ffe92b0 0x40107233:0x3ffe92d0 0x40107390:0x3ffe9300 0x40107bfd:0x3ffe9320 

I am still not able to test WiFi over the Base method (limitation of WiFi here) but hope to test it soon.

**Pull request closed without merging**
