### PR TITLE
Independent NTRIP client state machine

### PR DESCRIPTION
**Pull request by LeeLeahy2**
This change creates a state machine for the NTRIP client which is independent from the Rover state machine.

Remove WiFi states from Rover state machine.  The initial Rover state attempts to start the NTRIP client if it is enabled.  Operations fails back to Bluetooth when the RTK fails to establish a WiFi connection after 3 attempts.  This handles the WiFi out of range, connection timeout and bad SSID or password cases.  When the WiFi connection is made, the state machine will attempt to make the NTRIP client connection.  Again, after three failed attempts operation will fail back to Bluetooth.  Once the NTRIP client connection is established, any failure will tear down the NTRIP client and WiFi connections and then try to reestablish these connections.  Fall back to Bluetooth will only occur in the two cases above.

Once the NTRIP client connection is made to the NTRIP Caster, the data received from the caster is passed to the GPS radio.

### CODE REVIEW

**Comment by LeeLeahy2** [comment]
This change is 8 commits on top of pull request 152.

**Comment by nseidle** [comment]
Sorry for the delay in reviewing. I unfortunately get a guru mediation panic on RTK Facet:

Step to reproduce:

* Start unit in Rover mode
* Enable NTRIP Client and give WiFi credentials
* Allow unit to get NTRIP data and RTK lock
* Press Setup to change mode to Base. 
* Device enters base but panics after 3 seconds of Survey-In.

Are you familiar with the [ESP32 Exception Decoder](https://github.com/me-no-dev/EspExceptionDecoder)? Looks like line 83 of NtripClient.ino (bool ntripClientConnect()) is causing explosion.

Decoding stack results
0x400d63d4: ntripClientConnect() at C:\Users\nathan.seidle\Dropbox\Projects\SparkFun_RTK_Firmware\Firmware\RTK_Surveyor/NtripClient.ino line 83
0x400e27b1: ntripClientUpdate() at C:\Users\nathan.seidle\Dropbox\Projects\SparkFun_RTK_Firmware\Firmware\RTK_Surveyor/NtripClient.ino line 280
0x400e60f4: loop() at C:\Users\nathan.seidle\Dropbox\Projects\SparkFun_RTK_Firmware\Firmware\RTK_Surveyor/RTK_Surveyor.ino line 497
0x40109c45: loopTask(void*) at C:\Users\nathan.seidle\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.0\cores\esp32\main.cpp line 50

Serial output: 
10:18:47.702 -> 
State: Base - Not Started
10:18:49.665 -> [ 22808][D][Form.ino:155] stopWebServer(): Web Server Stopped
10:18:49.665 -> [ 22810][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
10:18:49.665 -> [ 22810][W][WiFiGeneric.cpp:852] _eventCallback(): Reason: 8 - ASSOC_LEAVE
10:18:49.665 -> [ 22816][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 3 - STA_STOP
10:18:49.712 -> Wi-Fi Stopped
10:18:49.712 -> [ 22846][D][Base.ino:13] configureUbloxModuleBase(): Skipping ZED Base configuration
10:18:49.852 -> [ 22978][D][NVM.ino:114] recordSystemSettingsToFileLFS(): Settings recorded to LittleFS: /SFE_Facet_LBand_Settings_0.txt
10:18:50.364 -> [ 23498][D][Form.ino:155] stopWebServer(): Web Server Stopped
10:18:50.782 -> [ 23933][I][BluetoothSerial.cpp:638] _init_bt(): device name set
10:18:50.782 -> Bluetooth broadcasting as: Facet L-Band Rover-2086
10:18:50.782 -> State: Base-Temp - Settle
10:18:50.782 -> [ 23938][I][BluetoothSerial.cpp:264] esp_spp_cb(): ESP_SPP_INIT_EVT
10:18:50.829 -> [ 23942][I][BluetoothSerial.cpp:271] esp_spp_cb(): ESP_SPP_INIT_EVT: slave: start
10:18:50.829 -> [ 23955][I][BluetoothSerial.cpp:372] esp_spp_cb(): ESP_SPP_START_EVT
10:18:50.829 -> [ 23989][D][WiFiClient.cpp:528] connected(): Disconnected: RES: -1, ERR: 113
10:18:50.829 -> NTRIP Client connection dropped
10:18:50.876 -> [ 23989][D][Form.ino:155] stopWebServer(): Web Server Stopped
10:18:50.922 -> Waiting for Horz Accuracy < 1.00 meters: 0.01
10:18:50.922 -> 
Survey started. This will run until 60 seconds have passed and less than 5.000 meter accuracy is achieved.
10:18:51.063 -> 
State: Base-Temp - Survey Started
10:18:52.091 -> [ 25221][D][System.ino:81] stopBluetooth(): Bluetooth turned off
10:18:52.091 -> Wi-Fi connecting to sparkfun-guest
10:18:52.091 -> [ 25236][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 0 - WIFI_READY
10:18:52.091 -> [ 25238][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 2 - STA_START
10:18:52.183 -> Time elapsed: 0 Accuracy: 0.03 SIV: 26
10:18:52.838 -> Time elapsed: 0 Accuracy: 0.03 SIV: 26
10:18:52.838 -> Batt (28%): Voltage: 3.78V Charging: 1.04%/hr Yellow
10:18:52.838 -> 
Time elapsed: 2 Accuracy: 0.03 SIV: 26
10:18:53.770 -> Time elapsed: 2 Accuracy: 0.03 SIV: 26
10:18:54.189 -> [ 27338][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
10:18:54.237 -> [ 27387][D][WiFiGeneric.cpp:831] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
10:18:54.237 -> [ 27387][D][WiFiGeneric.cpp:880] _eventCallback(): STA IP: 10.8.252.127, MASK: 255.255.252.0, GW: 10.8.252.1
10:18:54.284 -> Time elapsed: 3 Accuracy: 0.03 SIV: 26
10:18:54.284 -> Wi-Fi IP address: 10.8.252.127
10:18:54.284 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

**Comment by LeeLeahy2** [comment]
Fixed

**Comment by nseidle** [comment]
Working well now. Thanks! I'll merge and continue to test.

**Comment by LeeLeahy2** [comment]
Hi Nathan,

Would you please take a look at pull request 152?

Pull request 160 is built on top of pull request 152.  The panic issue is
most likely caused by not properly checking if ntripClient is allocated.
The dynamic allocation (new / delete) of ntripClient was introduced in pull
request 160.

Thanks for your help,
Lee Leahy
(808) 692-3394

**Pull request merged**
