### PR TITLE
Improve NTRIP Client

### PR DESCRIPTION
**Pull request by DavidBerschauer**
This PR contains 2 changes:
- Increase the character limit of the NTRIP caster host setting from 30 to 45
   - This enables the usage of e.g. openservice-sapos.niedersachsen.de
   - This limitation was only present in the web interface
-  Add the HTTP Accept header in the NTRIP request when using authorization. The NTRIP client was tested with openservice-sapos.niedersachsen.de resulting in a 403 response even with valid credentials. Adding the header did the trick

### CODE REVIEW

**Comment by nseidle** [comment]
This is a fine idea but [this](https://github.com/sparkfun/SparkFun_RTK_Firmware/pull/640/files#diff-26a0478572b82267c04af3611e64b166efb78824c46eeb27e5a5e9e111e7be89L275) is breaking the ability to connect to rtk2go.com. Is there another solution that will allow both?

**Comment by DavidBerschauer** [comment]
Unfortunately I can't test with rtk2go.com. What about trying out both? If the NTRIP client can't connect with the Accept header, the next retry is done without the header. 
I woud not add a setting for that, because it is already difficult to figure out, whats wrong with the NTRIP client, if you can't get RTK float or RTK fix.

SAPOS also works with this Accept header: ```Accept: rtk/rtcm, dgps/rtcm```
Does it work with rtk2go.com?

**Comment by DavidBerschauer** [comment]
I'm sorry, my fault! I just verified that openservice-sapos.niedersachsen.de is working without the Accept header. It must have been another problem with my test setup.

**Comment by nseidle** [comment]
No problem. I'm going to close this PR. Please let me know if changes need to be made in the future.

**Comment by DavidBerschauer** [comment]
Alright. But the increased limit of characters for the NTRIP caster host is still needed for openservice-sapos.niedersachsen.de. I already reverted the change with the Accept header so that is the only diff in this PR.

**Comment by nseidle** [comment]
Ah! My mistake. Thanks! Merging.

**Pull request merged**
