### PR TITLE
Captive Portal for easy configuration

### PR DESCRIPTION
**Pull request by DavidBerschauer**
This pull request shows the configuration website as a [captive portal](https://en.wikipedia.org/wiki/Captive_portal) for reducing the number of steps required to configure the RTK receiver via the web interface.

Therefore it is required to run a DNS server on the ESP32 and intercept the automatic requsts by the connected mobile device. The intercepted request on the in the wiki defined URLs are answered by a additional AsyncWebHandler that provides a small website redirecting the user to the configuration web interface. This extra step is required, because a simple HTTP redirct did not work in testing and the default index.html did not request the configuration data correctly. 

Previously the user would connect to the WiFi AP, read the IP on the RTK Express screen, type the IP into the browser and configure the receiver. With this change, the user simply connects to the WiFi AP and is automatically directed to the configuration page without even without knowing what an IP address is.

The code is tested with a RTK Express and iOS/Android clients.

### CODE REVIEW

**Comment by nseidle** [comment]
This looks like a great add! Thanks! I am slightly concerned with RAM usage (we are very low) but since this operates in the Config mode only (no BT) we should be fine. I'll try to get tested next week after the holiday.

**Comment by nseidle** [comment]
This works well! Thanks. Let me have @PaulZC test on iOS before I merge.

**Comment by PaulZC** [comment]
Cool... I'll try and do this tomorrow.

**Comment by PaulZC** [comment]
Working well on iOS

image

**Comment by PaulZC** [comment]
But, just a "heads up" that with verbose debugging turned on, I am seeing lots of there:

```
[ 27446][E][WiFiUdp.cpp:219] parsePacket(): could not receive data: 9
[ 27458][D][Form.ino:360] stopWebServer(): Web Server Stopped
[ 27458][E][WiFiUdp.cpp:219] parsePacket(): could not receive data: 9
[ 27470][D][Form.ino:360] stopWebServer(): Web Server Stopped
[ 27470][E][WiFiUdp.cpp:219] parsePacket(): could not receive data: 9
[ 27482][D][Form.ino:360] stopWebServer(): Web Server Stopped
[ 27482][E][WiFiUdp.cpp:219] parsePacket(): could not receive data: 9
[ 27493][D][Form.ino:360] stopWebServer(): Web Server Stopped
[ 27493][E][WiFiUdp.cpp:219] parsePacket(): could not receive data: 9
[ 27505][D][Form.ino:360] stopWebServer(): Web Server Stopped
[ 27505][E][WiFiUdp.cpp:219] parsePacket(): could not receive data: 9
[ 27516][D][Form.ino:360] stopWebServer(): Web Server Stopped
[ 27516][E][WiFiUdp.cpp:219] parsePacket(): could not receive data: 9
[ 27528][D][Form.ino:360] stopWebServer(): Web Server Stopped
[ 27528][E][WiFiUdp.cpp:219] parsePacket(): could not receive data: 9
```

**Comment by nseidle** [comment]
@PaulZC - Thanks! Those verbose debugs have started since @LeeLeahy2 recent work. I don't believe it's connected to this PR.

**Pull request merged**
