### PR TITLE
Add information on iOS BLE to Bluetooth Page

### PR DESCRIPTION
**Pull request by JonathanLeeDeKock**
I got stuck here for half a day trying to configure the device to work with my iPhone.  I couldn't understand why it wouldn't pair with my phone when it paired just fine with my computer.  Finally I read ahead in the instructions and at the very bottom of the GIS software page I found this nugget of information.  I almost missed it since most of the GIS software was not relevant to me.  I recommend moving this nugget of information up a page so others don't get stuck here quite so easily.

### CODE REVIEW

**Comment by gdt** [comment]
I don't think iti is really true that iOS doesn't support SPP.  I think it's more accurate to say that iOS declines to interoperate with SPP that has not paid a fee.   As an example i have an OBD2 adpator that works with classic Bluetooth on iOS.

**Comment by gdt** [comment]
One could say something like "iOS does not interoperate with the standards-compliant Bluetooth SPP imlementation in the RTK Express, but it does work with the BLE implementation".  That still steers the users in the right direction.

**Comment by JonathanLeeDeKock** [comment]
Happy to have it say whatever you'all think is right.  Note that I just pulled this exact working from the gis_software.md page, so if changing one, they both should be changed.

**Comment by nseidle** [comment]
Ya, iOS allows SPP but you have to get a special chip, or get approved, or something. I don't really care to dig into it.

@JonathanLeeDeKock - Sorry for the wasted time and many thanks for the PR! Merging.

**Pull request merged**
