### PR TITLE
Add BLE Support

### PR DESCRIPTION
**Pull request by burnsed**
See PR #235 for the original description and change. 

Note: I'd like to test this change a bit more after issue #237 is resolved. I'm not 100% sure that bug is only adding noise. It might also be mangling some of the GNSS messages as well.

@nseidle I think I addressed your first to points. For the 3rd (bluetoothSerial library moving to its own repo soon), is there anything you'd like me to do as part of this change for that? I think it should be pretty easy to split the two bluetooth serial libraries into external dependencies once you're ready.

Thanks!

### CODE REVIEW

**Comment by burnsed** [comment]
FYI, I got about 7hrs of continuous use/testing done over 2 days. Everything worked well. @nseidle I think the change is ready.

**Comment by nseidle** [comment]
Hi @burnsed - I keep trying to merge this but am having problems resolving the conflicts. My apologies for the delay! If you have the chance to re-base, I promise I won't ask again. If not, I understand, and I'll force it.

**Comment by burnsed** [comment]
@nseidle ok, should be good to go. I did a quick sanity test to make sure the BLE changes still work with everything new.

**Comment by nseidle** [comment]
Many thanks! We'll get this into the next release.

**Pull request merged**
